name = "dmm-cast-webdav"
main = "src/app.js"
compatibility_date = "2024-09-23"
# account_id = ""
workers_dev = true
preview_urls = false

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "src/app.js"

[dev]
# Ignore the generated public-assets.js to avoid build loops
ignore_rules = ["src/public-assets.js"]